//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lumen_Merch_Store.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Catalogue_uk {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Catalogue_uk() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Lumen_Merch_Store.Resources.Catalogue_uk", typeof(Catalogue_uk).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        internal static string FilterTitle_Search {
            get {
                return ResourceManager.GetString("FilterTitle_Search", resourceCulture);
            }
        }
        
        internal static string FilterTitle_Categories {
            get {
                return ResourceManager.GetString("FilterTitle_Categories", resourceCulture);
            }
        }
        
        internal static string FilterTitle_Universes {
            get {
                return ResourceManager.GetString("FilterTitle_Universes", resourceCulture);
            }
        }
        
        internal static string FilterTitle_Price {
            get {
                return ResourceManager.GetString("FilterTitle_Price", resourceCulture);
            }
        }
        
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        internal static string PriceFrom {
            get {
                return ResourceManager.GetString("PriceFrom", resourceCulture);
            }
        }
        
        internal static string PriceTo {
            get {
                return ResourceManager.GetString("PriceTo", resourceCulture);
            }
        }
        
        internal static string PriceRange {
            get {
                return ResourceManager.GetString("PriceRange", resourceCulture);
            }
        }
        
        internal static string FoundTotal {
            get {
                return ResourceManager.GetString("FoundTotal", resourceCulture);
            }
        }
        
        internal static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        internal static string TryChangeSearch {
            get {
                return ResourceManager.GetString("TryChangeSearch", resourceCulture);
            }
        }
        
        internal static string Sort_Default {
            get {
                return ResourceManager.GetString("Sort_Default", resourceCulture);
            }
        }
        
        internal static string Sort_PriceAsc {
            get {
                return ResourceManager.GetString("Sort_PriceAsc", resourceCulture);
            }
        }
        
        internal static string Sort_PriceDesc {
            get {
                return ResourceManager.GetString("Sort_PriceDesc", resourceCulture);
            }
        }
        
        internal static string Sort_Newest {
            get {
                return ResourceManager.GetString("Sort_Newest", resourceCulture);
            }
        }
        
        internal static string Sort_Label {
            get {
                return ResourceManager.GetString("Sort_Label", resourceCulture);
            }
        }
        
        internal static string Product_From {
            get {
                return ResourceManager.GetString("Product_From", resourceCulture);
            }
        }
        
        internal static string Product_Size {
            get {
                return ResourceManager.GetString("Product_Size", resourceCulture);
            }
        }
        
        internal static string Product_Quantity {
            get {
                return ResourceManager.GetString("Product_Quantity", resourceCulture);
            }
        }
        
        internal static string Product_AddToCart {
            get {
                return ResourceManager.GetString("Product_AddToCart", resourceCulture);
            }
        }
        
        internal static string Product_AddToFav {
            get {
                return ResourceManager.GetString("Product_AddToFav", resourceCulture);
            }
        }
        
        internal static string Stock_None {
            get {
                return ResourceManager.GetString("Stock_None", resourceCulture);
            }
        }
        
        internal static string ViewProducts {
            get {
                return ResourceManager.GetString("ViewProducts", resourceCulture);
            }
        }
        
        internal static string UniversesNotFound {
            get {
                return ResourceManager.GetString("UniversesNotFound", resourceCulture);
            }
        }
        
        internal static string UnknownUniverse {
            get {
                return ResourceManager.GetString("UnknownUniverse", resourceCulture);
            }
        }
        
        internal static string Untitled {
            get {
                return ResourceManager.GetString("Untitled", resourceCulture);
            }
        }
    }
}
